### ISSUE TITLE
What is a computational complexity of queuing nearest point? 

### ISSUE THREAD

**Issue by ababo** [sdd/kiddo_v1#10]
For unknown reason the kiddo library takes about 1000x more time than Python's `sklearn.neighbors.KDTree` for very large datasets (like several millions of points). Can you confirm we have O(log(n)) for the nearest point query?

**Comment by sdd** [comment]
Of course, as with all kd trees an nn query is O(log(n)) in Kiddo.

Have you built in release mode? 

Does your timing include the time to build the tree as well?

I might be able to help track down the bottleneck if you can share some example code?

**Comment by ababo** [comment]
Here is the code:
```rust
fn remove_outliers(clouds: &mut [Vec<Point3>], distance: f64) {
    let count = clouds.iter().flatten().count();
    if distance.is_infinite() || count < 2 {
        return;
    }

    let mut kdtree = KdTree::with_capacity(3, count);
    for point in clouds.iter().flatten() {
        kdtree.add(*point.coords.as_ref(), ()).unwrap();
    }

    let squared_distance = distance * distance;

    for points in clouds.iter_mut() {
        let mut j = 0;
        for i in 0..points.len() {
            let (dist, _) = kdtree
                .nearest(points[i].coords.as_ref(), 2, &squared_euclidean)
                .unwrap()[1];
            if dist <= squared_distance {
                points.swap(i, j);
                j += 1;
            }
        }
        points.truncate(j);
    }
}

```

**Comment by ababo** [comment]
It's based on `mrhooray/kdtree-rs` rather than `kiddo`, but the latter behaves similarly (though `kiddo` seems to be 15% faster).

**Comment by sdd** [comment]
I'll take a look at this for you when I'm free later today, to see if I can speed it up. Could you also share the faster Python code that does the same, for comparison?

**Comment by ababo** [comment]
```python
kdt = KDTree(cloud, leaf_size=30, metric='euclidean')
dist, idx = kdt.query(cloud, k=2, return_distance=True, sort_results=True)
```

**Comment by sdd** [comment]
I'm just looking at your remove_outliers function, to try to understand what is happening. It looks like you are trying to reject all points whose distance to the nearest other point in the tree is greater than a specified distance, is that right?

**Comment by ababo** [comment]
Correct.

**Comment by sdd** [comment]
I see. What if you have a cluster of a million points all close to each other, and then two points that are far from that cluster but very close to each other? This algo would not consider them to be outliers as they are close to each other, even though they are outliers statistically?

**Comment by ababo** [comment]
Yes, that's the limitation of this algorithm, but I get pretty descent
results using it, so the problem is not in the algorithm itself, but rather
in its performance.

**Comment by sdd** [comment]
Ok, I've created a couple of quick-and-dirty scripts to compare the two, with random trees containing 10 million items (each item is a random point in three dimensions).

I first create an array of 10M points and then a tree containing every item in that array, and print out the setup time.
Then I query the tree for the nearest 2 points for each point in the array, as per your example.

In python, I did this:

```python
import numpy as np
from sklearn.neighbors import KDTree
import time

SIZE = 10_000_000;

np.random.seed(0)

start = time.time()
print("starting setup")
cloud = np.random.random((SIZE, 3))
kdt = KDTree(cloud, leaf_size=30, metric='euclidean')
end = time.time()
print(f'setup complete in {1000*(end-start)}ms')

start = time.time()
print("starting query")
dist, idx = kdt.query(cloud, k=2, return_distance=True, sort_results=True)
end = time.time()
print(f'query complete in {1000*(end-start)}ms')
```

The results were as follows:

```bash
 python bench-sklearn-kdtree.py 
starting setup
setup complete in 29307.855129241943ms
starting query
query complete in 87912.35876083374ms
```

So, after ~29s of setup time, the query took ~88s.

In Rust, I used the following code to do the same:

```rust
extern crate kiddo;

use kiddo::KdTree;
use std::time::Instant;
use kiddo::distance::squared_euclidean;

const SIZE: usize = 10_000_000;

fn random_point() -> [f64; 3] {
    rand::random()
}

fn main() {
    println!("starting setup");
    let pre_setup = Instant::now();

    let mut points = vec![];
    for _ in 0..SIZE {
        points.push(random_point());
    }

    let mut kdtree = KdTree::new();
    for i in 0..points.len() {
        kdtree.add(&points[i], i).unwrap();
    }

    println!("Setup time: {}ms", pre_setup.elapsed().as_millis());

    let pre_query = Instant::now();
    println!("starting query");

    let results: Vec<_> = points.iter().map(|p|
        kdtree.nearest(p, 2, &squared_euclidean).unwrap()
    ).collect();

    println!("Query time: {}ms", pre_query.elapsed().as_millis());
}

```

and the results were as follows:

```bash
 ./target/release/kiddo-remove-outliers 
starting setup
Setup time: 13250ms
starting query
Query time: 52200ms
```

Setup was ~13s and the query took ~52s. The Python SciKit Learn version of the query took 1.7x longer.

**Comment by ababo** [comment]
That's correct. Thank you!

As it turned down, the culprit is `::with_capacity()` constructor. For unknown reason it slowed down implementation by many orders of magnitude. I guess we have a bug here.

I close the issue.

**Comment by sdd** [comment]
I don't think it's a bug. `with_capacity` will affect the time taken by both building and querying. Having a capacity of 3 items per node is sub optimal, but not a bug. I played around with my example above and found that I got the best performance by using `with_capacity(30)` rather than the default capacity of 16 that you get with `new()`. The speedup as not huge though - the query went down to 49s from 52s.

Anyway, glad you got it working! 👍🏼

**Comment by ababo** [comment]
I just thought the capacity matches the number of points added.

**Comment by sdd** [comment]
Aah I see - I'll update the docs on `with_capacity` to make it clearer what it actually does.

**Comment by jscheid** [comment]
This is a bit of a footgun considering that `Vec::with_capacity`, `HashSet::with_capacity`, `BinaryHeap::with_capacity`, `SmallVec::with_capacity` etc. all specify the number of total elements that can be stored in the structure. Perhaps it should be deprecated and replaced by a function `with_per_node_capacity` or such?

**Comment by ababo** [comment]
@jscheid IMO that sounds good.

**Comment by sdd** [comment]
`Vec::with_capacity`, `HashSet::with_capacity`, `BinaryHeap::with_capacity`, `SmallVec::with_capacity` do **not** specify the total / maximum number of elements that can be stored in the structure. They specify the number that can be stored _before triggering a memory reallocation_.

See here: https://doc.rust-lang.org/std/vec/struct.Vec.html#capacity-and-reallocation and the great piece of example code here https://doc.rust-lang.org/std/vec/struct.Vec.html#examples-2 for a demonstration.

**Comment by jscheid** [comment]
I'm aware, but the point still stands. With Vec etc., you go "I have 100 things I want to put in here efficiently (without triggering reallocation) so I use `with_capacity(100)`". But if you do the same with `KdTree` you're going to end up with an inefficient setup, or am I missing something?

**Comment by sdd** [comment]
No, you're right, you're not missing anything: the docs do mention that this is the per-node capacity but for consistency with the behaviour of `with_capacity` in other collections it should probably be named differently.

I'll rename it. Thanks for the input.

**Comment by sdd** [comment]
Would this be better? Any suggestions to improve further?

![image](https://user-images.githubusercontent.com/323439/141777417-93b8f957-fec0-43f2-ab8e-b16c38ecc53f.png)

**Comment by sdd** [comment]
Released as https://crates.io/crates/kiddo/0.2.0

**Comment by jscheid** [comment]
That was quick, thanks @sdd!
