### ISSUE TITLE
serialization kd tree 

### ISSUE THREAD

**Issue by niyue** [sdd/kiddo_v1#17]
Hi there,

Is it supported to serialize the kd tree onto disk and probably mmap it to use the kd tree file as an persisted index? I read the documentation but it doesn't mentioned this kind of usage. Thanks.

**Comment by sdd** [comment]
Hi,

Yes, serde can be used to serialise and deserialize the tree. I can post
some examples of serializing / deserializing to disk if you'd like.

**Comment by niyue** [comment]
> I can post some examples of serializing / deserializing to disk if you'd like

Thanks so much and that will be great. Do you think if it will work if the file is accessed via memory map?

**Comment by sdd** [comment]
Something along these lines will work - this is taken from a project that is successfully saving and loading trees to disk.
The below will serialize the Kiddo kdtree from the example in the docs to a file in gzipped bincode format, and then read in that file to deserialize it back into a Kiddo kdtree instance.

```rust
use kiddo::KdTree;
use kiddo::distance::squared_euclidean;
use flate2::read::GzDecoder;
use flate2::write::GzEncoder;
use flate2::Compression;
use std::fs::File;
use std::path::Path;

let a: ([f64; 2], usize) = ([0f64, 0f64], 0);
let b: ([f64; 2], usize) = ([1f64, 1f64], 1);
let c: ([f64; 2], usize) = ([2f64, 2f64], 2);
let d: ([f64; 2], usize) = ([3f64, 3f64], 3);

let mut kdtree = KdTree::new()?;

kdtree.add(&a.0, a.1)?;
kdtree.add(&b.0, b.1)?;
kdtree.add(&c.0, c.1)?;
kdtree.add(&d.0, d.1)?;

let filename: String = "tree.bincode.gz";
 
let file_to_write_to = File::create(filename).expect("Could not open file to write to");
let encoder = GzEncoder::new(file_to_write_to, Compression::default());
bincode::serialize_into(encoder, &tree).expect("could not serialize tree");

let file_to_read = File::open(filename.into()).expect("could not open tree file");
let decompressor = GzDecoder::new(file_to_read);
let reloaded_tree: KdTree<f64, usize, 2> = bincode::deserialize_from(decompressor).expect("could not deserialize file into tree");

assert_eq!(reloaded_tree.size(), 4);

assert_eq!(
    kdtree.nearest(&a.0, 1, &squared_euclidean).unwrap(),
    vec![(0f64, &0)]
);
```

**Comment by niyue** [comment]
Thanks so much for the help. I will check it out.
