### ISSUE TITLE
[Question] Possible to build a trait for generics?

### ISSUE THREAD

**Issue by Heiss** [sdd/kiddo_v1#22]
Hey,

first things first: Thank you for your work on this library.

Is it possible to use your library with custom structs? So i can add a struct to the kdtree and find the closest object? I want to use your library in a project, where i want to show a line between two or more objects. It would be super useful, if i can get the object with `nearest_one` instead of only the coordinates. Otherwise i would need to find the object in a list again with the given coordinates.

I could imagine something like the following snippet: (holds syntax errors, sorry but i think this shows the idea i would like to see implemented)

```rust=
struct Customstruct {
  val: String,
  trigger: bool,
  x: f32,
  y: f32,
  z: f32
}

impl Customstruct {
  fn new(val: &str, trigger: bool, x: f32, y: f32,z: f32) -> Self {
    Customstruct {
       val, trigger, x, y, z
    }
  }
}

trait Point {
  fn get_points(&self) -> &[A, k] // Something kiddo needs to work
}

impl Point for Customstruct {
  fn get_points(&self) -> &[A,k] {
    &[self.x, self.y, self.z]
  }
}

fn main() {
  let mut kdtree: KdTree<Customstruct> = KdTree::new();
  let struct = Customstruct::new("Something", False, 0, 1, 2);
  kdtree.add(struct)?; // beware here! The kdtree owns the struct now. Otherwise i need another struct to hold the data. Maybe another binary tree?
  let nearest: &Customstruct = kdtree.nearest_one(&struct, &squared_euclidean)?;
}
```

Is this already possible? Or should i fork your work and try to do it myself? Then I appreciate some hints to get this done.

Thank you for your help and ideas.

Greetings

**Comment by sdd** [comment]
This is already possible. kiddo's `nearest_one` returns a tuple. The first entry in the tuple is the distance. The second entry is a reference to the element itself.

Something like this:

```rust
let mut tree: KdTree<f32, Customstruct, 3> = KdTree::new();

let struct1 = Customstruct::new("Something", False, 0, 1, 2);
let struct2 = Customstruct::new("Something Else", False, 3, 4, 5);

tree.add(&[0, 1, 2], struct1)?;
tree.add(&[3, 4, 5], struct2)?;

let (dist, nearest) = tree.nearest_one(&[1.0, 2.0, 5.1], &squared_euclidean)?;

println!("nearest: {:?}", &nearest.val);
```

**Comment by Heiss** [comment]
Oh yes, of course. Thank you for your example. I ignored the data parameter in [add](https://docs.rs/kiddo/latest/kiddo/kiddo/struct.KdTree.html#method.add). Thank you very much for your fast answer. Have a great day. :)

**Comment by sdd** [comment]
You're welcome, have a great day too Peter! 👍🏼
