### ISSUE TITLE
Variable number of dimensions

### ISSUE THREAD

**Issue by cagucor** [sdd/kiddo_v1#31]
Hi Everyone!

My application involves a variable number of dimensions in data files, so that information is not known at compile time. I am reading the file into a `Vec<Vec<f64>>`. 
I tried converting the vector to a slice to use the `add` method, but get the error: `rustc: mismatched types expected reference &[_; _]  found reference &[f64]`. I also want to split up my code into separate functions and am not sure how to use `KdTree<A, T, K>` as a generic for function input and output with the constant K.

I think this problem is due to my lack of understanding of rust generics, but if someone can point me in the right direction that would be greatly appreciated!

**Comment by sdd** [comment]
Hi Carlos. Unfortunately I think you'll be out of luck - the values of Rust generics need to be known at compile time, and in Kiddo the number of dimensions is a generic parameter. Sorry about that! I think you'll need to use a different library.
