### ISSUE TITLE
All points satisfying set of linear inequalities

### ISSUE THREAD

**Issue by reinismx** [sdd/kiddo_v1#34]
I would like to be able to iterate over all points (x, y) in a set of points such that `x <= x_limit` and `y <= y_limit`.

As far as I can tell, the library currently has no support for such a query. However, in my understanding, a 2D `KdTree` would be a good data structure for efficiently implementing something like that.

I'm thinking it could be provided as a function `iter_quadrant(&self, point: &[A; K], sides: &[Side; K])` and

```rust
enum Side {
  Above,
  Below,
}
```

Any thoughts on this? Would it be general enough? It could be generalized by accepting any set of linear inequalities as the limits (e.g. "what points lie within this triangle"?). This would increase the complexity a lot though, and I don't need it for my use case.

**Comment by sdd** [comment]
I think you might be able to do this by using a "taxi distance" metric rather than squared_euclidean.
