### ISSUE TITLE
Failed to build in rustc 1.57.0-nightly

### ISSUE THREAD

**Issue by Mr-Milk** [sdd/kiddo_v1#6]
```
--> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/kiddo-0.1.4/src/lib.rs:2:12
  |
2 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^ feature has been removed
  |
  = note: removed in favor of `#![feature(adt_const_params]` and `#![feature(generic_const_exprs)]
```

Hi, thanks for such a great crate. Do you mind take a look at this? Should be a simple fix.

**Comment by sdd** [comment]
Hi! Sure, happy to fix, but will this cause builds to break on older rustc versions? I'll do some checks and see if I can find a solution that works for pre and post 1.57

**Comment by sdd** [comment]
I guess older rustc users will have their cargo lockfile anyway, and can easily upgrade. I've merged https://github.com/sdd/kiddo/pull/8 which fixes this, amongst other things.

Glad you appreciate the crate as well! Thanks!

**Comment by sdd** [comment]
Fix released in https://crates.io/crates/kiddo/0.1.5
